language: python

python:
    - "3.6"

sudo: required

cache: pip

env:
    - AIL_HOME=$TRAVIS_BUILD_DIR AIL_BIN=$TRAVIS_BUILD_DIR/bin/ \
      AIL_FLASK=$TRAVIS_BUILD_DIR/var/www/ AIL_REDIS=$TRAVIS_BUILD_DIR/redis/src/ \
      AIL_LEVELDB=$TRAVIS_BUILD_DIR/redis-leveldb/ PATH=$AIL_HOME:$AIL_REDIS:$AIL_LEVELDB:$PATH

dist: xenial

before_install:
  - chmod +x ./installing_deps.sh

install:
    - ./installing_deps.sh
    - pip install coveralls codecov nose

script:
    - pushd bin
    - ./LAUNCH.sh -l
    - popd
    - cd tests
    - nosetests --with-coverage --cover-package=../bin -d

deploy:
  provider: heroku
  api_key: d3acf45f-dd7c-4383-b23e-18658fbeb738
    secure: KEY
  app:ail-tfm
  on:
    repo: redpanda87/AIL-framework-master


after_success:
    - codecov
    - coveralls
